# Note: This file is modified from one generated by `nixos-generate-config`.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "main-1z9h4t/shape";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/nix" =
    { device = "main-1z9h4t/shape/nix";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/srv" =
    { device = "main-1z9h4t/shape/srv";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/state" =
    { device = "main-1z9h4t/shape/state";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/tmp" =
    { device = "main-1z9h4t/shape/tmp";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/usr/local" =
    { device = "main-1z9h4t/shape/usr/local";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/var/cache" =
    { device = "main-1z9h4t/shape/var/cache";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/var/games" =
    { device = "main-1z9h4t/shape/var/games";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/var/lib" =
    { device = "main-1z9h4t/shape/var/lib";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/var/local" =
    { device = "main-1z9h4t/shape/var/local";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/var/log" =
    { device = "main-1z9h4t/shape/var/log";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/var/tmp" =
    { device = "main-1z9h4t/shape/var/tmp";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/boot" =
    { device = "boot-1z9h4t/shape";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/etc/nixos" =
    { device = "/state/etc/nixos";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/etc/cryptkey.d" =
    { device = "/state/etc/cryptkey.d";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/boot/efis/nvme-Samsung_SSD_970_EVO_Plus_2TB_S59CNM0R706239E-part2" =
    { device = "/dev/disk/by-uuid/9BC0-C3BF";
      fsType = "vfat"; options = [ "x-systemd.idle-timeout=1min" "x-systemd.automount" "noauto" ];
    };

  fileSystems."/boot/efis/nvme-Samsung_SSD_970_EVO_Plus_2TB_S59CNM0R706236Y-part2" =
    { device = "/dev/disk/by-uuid/9BC1-1A18";
      fsType = "vfat"; options = [ "x-systemd.idle-timeout=1min" "x-systemd.automount" "noauto" ];
    };

  swapDevices = [
    { device = "/dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_2TB_S59CNM0R706239E-part5"; randomEncryption.enable = true; }
    { device = "/dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_2TB_S59CNM0R706236Y-part5"; randomEncryption.enable = true; }
  ];
}
